tech-conferences/javascript-conferences

- README.md
> Removes Future Insights

- README.md
Conference for front end developers, with performance as this years theme
> Added Fronteers Spring Conference

- README.md
> Added NodeConf Argentina :tada:

- README.md
Adds ThunderPlains Developer Conference to the list
http://thunderplainsconf.com/
> Add ThunderPlains 2016 ⚡️

- README.md
Add Script'17 conference in Linz, Austria
> Add Script'17 conference in Linz, Austria

- 2016/README.md
I always see the name all lower case, but let me know if you want to change it.
> Added ffconf 2016

- README.md
> Added Universal JS Day

- README.md
Actually, first one Ukrainian's conference in the list :) 
Let me know if I should change something.
> Add JS fwdays '17

- README.md
JSFoo is India’s premier JavaScript conference hosted by HasGeek.
> Jsfoo bangalore

- README.md
https://activeingredients.info/call-for-speakers/
> adds Active Indgredients

- README.md
It had the right date, but it was not in the correct month section :man_shrugging:
> Place Active Ingredients in April instead of May

- README.md
Added NCDevCon - Oct 7-8 in Raleigh, NC
> Added NCDevCon

- README.md
Adds [MidwestJS](http://www.midwestjs.com/)
> Adds MidwestJS

- README.md
They have some problems with certificate on their website but AFAIK this will be fixed soon
> Add OdessaJS

- README.md
Announced here https://twitter.com/ChromiumDev/status/892770719448289280
> Add Chrome Dev Summit 2017

- README.md
Add that nice conference, as I've seen the `dotCSS` also appears in the list.
> Add SmashingConf in Freiburg, Germany

- conferences/2018/javascript.json
The dates were just announced on Twitter https://twitter.com/web_rebels/status/923255552699924482
The website is not updated at the time of submitting Pull Request.
> Added Web Rebels Oslo 2018

- conferences/2018/javascript.json
Chain React Conf - the React Native conference
July 2018 in Portland, OR
> Add Chain React conf

- conferences/2018/javascript.json
Added CFP details and Twitter account
> Added details about JazzCon.Tech

- conferences/2018/javascript.json
Fix the URL prefix for Frontend Developer Love conference
> Updating the broken URL

- conferences/2018/javascript.json
Updated the HolyJS 2018 Piter conference dates
> Updated dates of HolyJS

- conferences/2018/javascript.json
The date was announced on their Twitter handle https://twitter.com/NodeConfEU/status/948862872909766658
> Added NodeConf EU 2018

- conferences/2018/javascript.json
Tweet confirming the dates https://twitter.com/TypeScriptConf/status/949307214132588544
> Added TSConf 2018

- conferences/2018/javascript.json
Date confirmed in tweet https://twitter.com/dinosaur_js/status/954419446927503361
> Added DinosaurJS 2018

- conferences/2018/javascript.json
Hello, @prigara.
Could you add JS Fest?
With best regards from Ukraine.
> Added JS Fest 2018
